[package]
name = "objectif"
version = "0.1.0"
edition = "2021"

[dependencies]
objectif-core = { path = "objectif-core" }
objectif-derive = { path = "objectif-derive" }

[[bench]]
name = "bench1"
harness = false